<h2>Nastavení uživatele</h2>

<form method="post">
	<p>
		<label>Jméno:</label>
		<input type="text" name="name" value="<?=$_SESSION["data"]["name"]?>" required>
	</p>
	<p>
		<label>Něco o mně:</label>
		<textarea name="description" required><?=$_SESSION["data"]["description"]?></textarea>
	</p>
	<p>
		<label>Životopis (strukturovaný/esej):</label>
		<textarea name="cv" required><?=$_SESSION["data"]["cv"]?></textarea>
	</p>
	<p>
		<input type="submit" name="userSettings" value="Nastavit">
	</p>
</form>