<article>
	<h2><?=$article["title"]?></h2>
	<p><em>Naposledy editováno <?=$x->date($article["timestamp"], "d.m.Y");?>.</em></p>

	<?if( !$if ):?>
		<p><a href="<?=$base?>/explore/<?=$parent["url"]?>">zpět</a></p>
	<?endif?>

	<table>
		<?foreach( $children as $child):?>
			<tr><td>
				<a href="<?=$base?>/explore/<?=$child["url"]?>"><?=$child["title"]?></a>
			</td></tr>
		<?endforeach?>
	</table>

	<p><?=$article["content"]?></p>
</article>

<?=$comment->render( $article["article_id"] )?>