<!DOCTYPE html>
<html lang="cs">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Česká IT komunita - LitKeep</title>

    <link href="<?=$base?>/css/bootstrap.min.css" rel="stylesheet">
    <!--<link href='http://fonts.googleapis.com/css?family=Roboto+Slab&subset=latin,latin-ext,cyrillic-ext,cyrillic,greek-ext,greek,vietnamese' rel='stylesheet' type='text/css'>-->
    <link href="<?=$base?>/css/screen.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <?if( isset($_SESSION["flash"])) :?>
    <div class="alert alert-success" role="alert"><?=$_SESSION["flash"]?></div>
    <?endif?>

  	<header>
  		<div class="indent row">
  			<section class="col-md-2">
  				<a href="<?=$base?>"><img src="<?=$base?>/img/logo.png"></a>
  			</section>
  			<section class="col-md-4 down-5">
  				<form method="get">
  					<input type="text" class="search" placeholder="Explore through universe..." name="search">
  					<a href="#" id="searchSubmit"><span class="glyphicon glyphicon-search"></span></a>
  				</form>
  			</section>
  			<section class="col-md-6 down-15 right">
  				<ul class="nav horizontal">
              <li><a href="<?=$base?>/explore/root">Procházet</a></li>
            <?if( $_SESSION["logged"]):?>
    					<li><a href="<?=$base?>/logout">Odhlásit se</a></li>
    					<li><a href="#">Události <span>2</span></a></li>
    					<li class="profile"><a href="<?=$base?>/profile/<?=$_SESSION["data"]["id"]?>"><?=$_SESSION["data"]["name"]?></a></li>
            <?else:?>
              <li><a href="<?=$base?>/login">Přihlásit se</a></li>
            <?endif?>
  					<div class="clear"></div>
  				</ul>
  			</section>
  		</div>
  	</header>

  	<main>
  		<div class="indent row">
  			<section class="col-md-3">
                <?if( $showGroupMenu ):?>
                    <h2>Menu komunity</h2>
                    <ul class="nav vertical">
                        <li><a href="<?=$base?>/explore/souteze">Soutěže</a></li>
                        <li><a href="<?=$base?>/forum/<?=$group["url"]?>-group">Komunitní fórum</a>
                        <?if( $member["role"] == "Admin" ):?>
                        <li><a href="<?=$base?>/group/<?=$group["url"]?>/admin">Administrace</a></li>
                        <?endif?>
                    </ul>
                <?endif?>

  				<h2>Navigace</h2>
  				<ul class="nav vertical">
					<li><a href="<?=$base?>/explore/root">Procházet</a></li>
          <li><a href="<?=$base?>/forum">Diskuzní fórum</a></li>
					<?if( !$_SESSION["logged"] ):?>
						<li><a href="<?=$base?>/login">Přihlásit</a></li>
					<?else:?>
						<li><a href="<?=$base?>/profile/<?=$_SESSION["data"]["id"]?>">Profil</a></li>
            <li><a href="<?=$base?>/mail">Moje konverzace <span>2</span></a></li>
						<li><a href="<?=$base?>/logout">Odhlásit</a></li>
					<?endif?>
				  </ul>

          <?if( isset($_SESSION["logged"]) ):?>
  				<h2>Tvé komunity</h2>
  				<ul class="nav vertical">
                    <?foreach( $my_groups as $item ):?>
                        <li><a href="<?=$base?>/group/<?=$item["url"]?>"><?=$item["name"]?></a></li>
                    <?endforeach?>
  				</ul>
          <?endif?>

  				<h2>Tvé projekty</h2>
  				<ul class="nav vertical">
  					<li><a href="#">PHP eshop</a></li>
  					<li><a href="#">ASP .NET systém knihovny</a></li>
  				</ul>
  			</section>

  			<section class="col-md-9 row">