<h2><?=$identity["name"]?></h2>

		<table>
			<?if( $_SESSION["data"]["id"] == $identity["id"] ):?>
				<tr>
					<td><a href="<?=$base?>/settings/user">Nastavení</a></td>
				</tr>
			<?endif?>
		</table>

<p><?=$x->texy($identity["description"])?></p>

<h2>Životopis</h2>

<?if( empty($identity["cv"]) ):?>
	<p>Uživatel si nepřidal žádné CV.</p>
<?else:?>
	<p><a href="#">Stáhnout v PDF</a></p>
	<p><?=$x->texy($identity["cv"])?></p>
<?endif?>