			</section>
		</div>
  	</main>

  	<footer>
  		<div class="indent">
  			<div class="row">
	  			<div class="col-md-6">
	  				<img src="<?=$base?>/img/logo-white.png">
	  			</div>

	  			<div class="col-md-6 right">
	  				<p class="copyright">© <a href="#">LitKeep</a> 2015 - Všechen obsah je volně šiřitelný, pokud není uvedeno jinak.</p>
	  			</div>
	  		</div>

	  		<ul class="nav horizontal">
	  			<li><a href="#">Licenční podmínky</a></li>
	  			<li><a href="#">Soukromí uživatele</a></li>
	  			<li><a href="#">O projektu</a></li>
	  		</ul>
  		</div>
  	</footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>